name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get Fetch Tags
        run: git -c protocol.version=2 fetch --tags --progress --no-recurse-submodules origin
        if: "!contains(github.ref, 'refs/tags')"
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'zulu'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Get Release Version
        id: get_version
        run: VERSION=$(./gradlew currentVersion -q -Prelease.quiet) && echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
      - name: Upload sshj-plugin jar
        uses: actions/upload-artifact@v4
        with:
          # Artifact name
          name: Grails-Plugin-${{ steps.get_version.outputs.VERSION }}
          # Directory containing files to upload
          path: build/libs/rundeck-ec2-nodes-plugin-${{ steps.get_version.outputs.VERSION }}.jar
